version: 2
jobs:        
  clang_5_0:
    working_directory: /circileci_test
    docker:
      - image: enumack/buildcontainers:gtest-clang-5.0
    steps:
      - run: ssh-keyscan 192.30.253.113 >> ~/.ssh/known_hosts
      - checkout
      - run: make test && ./bin/gtest
  clang_4_0:
    working_directory: /circileci_test
    docker:
      - image: enumack/buildcontainers:gtest-clang-4.0
    steps:
      - run: ssh-keyscan 192.30.253.113 >> ~/.ssh/known_hosts
      - checkout
      - run: make test && ./bin/gtest

workflows:
  version: 2
  build_and_test:
    jobs:
      - clang_4_0
      - clang_5_0
