version: 2
jobs:
  build:
    working_directory: /circileci_test
    docker:
      - image: enumack/buildcontainers:clang-4.0.1
    steps:
      - checkout
      - run: cmake . -DCMAKE_CXX_COMPILER=$CXX && make && ctest --no-label-summary --parallel 4