version: 2
jobs:
  build:
    working_directory: /circleci_test
    docker:
      - image: enumack/buildcontainers:gtest-clang-5.0
    steps:
      - checkout
      - run: cmake .. && make && ./gtest_example
